### PR TITLE
Add Integrations section to docs

### PR DESCRIPTION
**Pull request by danielbayley**
See https://github.com/jashkenas/coffeescript/issues/4615#issuecomment-710384338

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
This is a good start! I think we should try to include as many high-quality ones as we can find. Like I’m sure there’s something for Webpack. Probably for Rollup, Parcel, etc.

Maybe group by topic? Like Linters, Build Tools, etc. Framework integrations is another category, like the Meteor Atmosphere package (I maintain that one), the Ember one, I’m sure there are others.

**Comment by danielbayley** [comment]
@GeoffreyBooth Ok, I added those and more… and also updated the Wiki to match 👍 

That's as much as I can/have time to find at the moment… Iv'e checked 'Allow edits by maintainers', so feel free to pick up the baton if you want to add more… Otherwise it should be pretty much ready to merge?

**Comment by GeoffreyBooth** [comment]
Just picking this up. I discovered that CoffeeLint has been revived in a new, actively maintained fork: https://coffeelint.github.io/ cc @helixbass.

**Comment by GeoffreyBooth** [comment]
@danielbayley I organized the integrations categories similarly to the Resources section, where they appear as subsections. This lets us add links for them in the sidebar. I also added Integrations to the top navbar, and a few links in the CoffeeScript 2 and transpilation sections.

Any notes on this or should I merge it in?

**Comment by edemaine** [comment]
FWIW, I read this over, and it looks good!

In checking the links I noticed https://marketplace.visualstudio.com/items?itemName=crisward.cjsx, with source at https://github.com/crisward/cjsx . This might be a path forward to fixing [syntax highlighting in vscode](https://github.com/microsoft/vscode/issues/117143) and [in atom](https://github.com/atom/language-coffee-script/issues/174).

**Comment by GeoffreyBooth** [comment]
> This might be a path forward to fixing [syntax highlighting in vscode](https://github.com/microsoft/vscode/issues/117143) and [in atom](https://github.com/atom/language-coffee-script/issues/174).

For JSX, you mean? Literate syntax is also horribly broken.

**Comment by danielbayley** [comment]
> I discovered that CoffeeLint has been revived in a new, actively maintained fork: https://coffeelint.github.io/ cc @helixbass.

@GeoffreyBooth Which fork is that?

**Comment by danielbayley** [comment]
> Any notes on this or should I merge it in?

@GeoffreyBooth Nice! Yeah sure, merge away…

**Comment by GeoffreyBooth** [comment]
> p.s The links under https://coffeescript.org#resources are broken in the current deployment, as they try to create a new page…

Can you be more specific? The links in the sidebar work for me, and the links under Resources go to external sites as expected (like for the GitHub repo etc.).

**Pull request merged**
