### PR TITLE
simplified test file skiping (#4996)

### PR DESCRIPTION
**Pull request by rdeforest**
_This is a re-creation of PR #4997 without the extraneous history. Original description follows._

Per discussion on #4893, managing exclusion of tests when newer features are required is currently non-obvious. The goal of this PR is to make maintenance of such exceptions easy and surprise-free.

The existing method was a hard-wired exception for the file 'async.coffee'. When I added async_iterators for #4893 I was surprised because I didn't know about the ```build:watch:harmony``` build target nor the hardwired exception in runTests. Now both the feature test and filename match are handled on the same lines near the top of Cakefile.

I included two currently unused pattern/feature pairs to demonstrate the intent and value of this approach. Both will likely be used for #4877 and #4893.

I didn't write a test for this change since it's a change to the test system.

After posting this I'm going to figure out how to remove the extra unrelated empty commits, but I wanted to get this out there before the weekend to follow through on my previous commitment.

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
You don't need to worry about your Git history. We squash commits when we merge into `master`. I encourage contributors to leave their history unmodified, so that others can work on the same branch without conflicts.

**Comment by rdeforest** [comment]
whoops. That extra commit was a no-op. I was trying to clean up my fork of the repo. Sorry for the distraction.

**Comment by GeoffreyBooth** [comment]
Did you mean to close this pull request? I think deleting your branch closed it automatically.

**Comment by rdeforest** [comment]
I did not mean to. Weird. I decided to help out in order to learn, but this wasn't what I had in mind. :)

It won't let me re-open since I deleted the branch, so I'll create a THIRD PR... Derp derp....

**Pull request closed without merging**
