### PR TITLE
Fix #5213: Update Babel options to restore MINIFY=false

### LINKED ISSUE #5213: Bug: MINIFY=false no longer generates deminified coffee-script.js?
### Input Code

In /bin/bash for version 1.10.0, I had the following:
<pre>
(Download coffeescript tarball from website and extract, then cd to working directory)
npm install
cake build
MINIFY=false cake build:browser
cp extras/coffee-script.js (destination)
</pre>

I'm aware via #4677 that extras/coffee-script.js has moved to docs/v2/coffeescript.js.  However, when I download and extract 2.4.1.tar.gz and run the `MINIFY=false cake build:browser`, I get a minified coffeescript.js.

### Expected Behavior
coffeescript.js is not minified.

### Current Behavior
coffeescript.js is minified.

Note:  It's entirely possible that my build instructions are wrong and this bug is invalid.  A quick glance at the Cakefile suggests that this part of it shouldn't have changed, though...

Please advise.

### PR DESCRIPTION
**Pull request by GeoffreyBooth**

### CODE REVIEW

**Comment by ajvincent** [comment]
It's better, but still a little compacted:
```bash
[ajvincent@localhost coffeescript]$ head lib/coffeescript-browser-compiler-legacy/coffeescript.js 
```
```javascript

/**
 * CoffeeScript Compiler v2.4.1
 * https://coffeescript.org
 *
 * Copyright 2011-2019, Jeremy Ashkenas
 * Released under the MIT License
 */
function _typeof(obj) { if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }

function _toArray(arr) { return _arrayWithHoles(arr) || _iterableToArray(arr) || _nonIterableRest(); }

```

**Comment by ajvincent** [comment]
Oh, but that appears to be an artifact of another library, not your changes:  looking closer, it is much more readable.  (Yes, it's also twice the size, but I asked for it, didn't I?)

**Comment by GeoffreyBooth** [comment]
The first 50 lines or so are functions added by Babel during transpilation, and that one-line style is just how Babel writes them. If you scroll a bit deeper into the file, you’ll see it’s readable.

**Comment by ajvincent** [comment]
OK, this is much better.  Thank you.

**Pull request merged**
