### PR TITLE
Prevent writing the same file several times (fixes #3753)

### LINKED ISSUE #3753: Compiler can write several times the same file without warning and producing garabage
When you compile several files like this

    coffee -o output/ -c a/somefile.coffee b/somefile.coffee

it writes the file `somefile.js` twice without warning, and if in the second writing the file was shorter, it produces bugs or syntax errors because you can see remains of the previous file at the end.

### PR DESCRIPTION
**Pull request by DiThi**

### CODE REVIEW

**Comment by lydell** [comment]
Any reason this hasn’t been merged? LGTM.

**Comment by jashkenas** [comment]
Rebase for a clean merge?

**Comment by DiThi** [comment]
Conflict was just in a compiled .js file.

**Comment by jashkenas** [comment]
See #3863. Can we fix this patch? Otherwise, we should revert it.

**Comment by EdwardReed** [comment]
@jashkenas Agreed

**Comment by jashkenas** [comment]
I'm going to revert this, then.

**Pull request merged**
