### PR TITLE
CoffeeScript 1.10.0

### PR DESCRIPTION
**Pull request by lydell**
I followed the steps I wrote after having made the 1.9.3 PR: https://github.com/jashkenas/coffeescript/wiki/%5BHowto%5D-Hacking-on-the-CoffeeScript-Compiler#11-preparing-a-new-release

Step 8:

> Make sure that you haven’t forgot to update the version number somewhere. If you update from 1.9.9, git grep '1\.9\.9' should only find matches in the change log.

However:

```
documentation/coffee/aliases.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/array_comprehensions.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/block_comment.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/cake_tasks.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/chaining.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/classes.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/comparisons.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/conditionals.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/constructor_destructuring.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/default_args.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/do.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/embedded.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/existence.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/expansion.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/expressions.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/expressions_assignment.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/expressions_comprehension.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/expressions_try.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/fat_arrow.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/functions.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/generators.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/heredocs.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/heregexes.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/interpolation.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/modulo.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/multiple_return_values.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/object_comprehensions.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/object_extraction.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/objects_and_arrays.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/objects_reserved.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/overview.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/parallel_assignment.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/patterns_and_splats.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/prototypes.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/range_comprehensions.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/scope.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/slices.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/soaks.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/splats.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/splices.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/strings.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/switch.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/switch_with_no_expression.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/try.js:// Generated by CoffeeScript 1.9.3
documentation/coffee/while.js:// Generated by CoffeeScript 1.9.3
documentation/index.html.js:      <%= releaseHeader('2015-09-04', '1.10.0', '1.9.3') %>
documentation/index.html.js:      <%= releaseHeader('2015-05-27', '1.9.3', '1.9.2') %>
index.html:  <a href="https://github.com/jashkenas/coffeescript/compare/1.9.3...1.10.0">1.10.0</a>
index.html:      <div class="anchor" id="1.9.3"></div>
index.html:  <a href="https://github.com/jashkenas/coffeescript/compare/1.9.2...1.9.3">1.9.3</a>
```

I’m very confused by the `documentation/coffee/*.js` files. The various commands I ran seem to have updated `documentation/js/*.js`, but not the ones in the `coffee` directory. Apparently @jashkenas updated those after my 1.9.3 PR (commit c37f284).

It feels like all `documentation/coffee/*.coffee` files have duplicate compiled versions comitted. There seems to be no `cake` command to update the `documentation/coffee/*.js` ones. What’s up here, and which ones are actually used?

---

Regarding the changelog, it might feel really small at only three items, but the last item (”Several minor bug fixes.”) includes _a lot_ of really good fixes. I just didn’t feel necessary to note them all in the changelog, since they don’t affect most CoffeeScript users.

Such a short changelog might also raise the question if we should release a version at all, but remember:

- Destructuring defaults have been awaited for a _long_ time. Let’s get ’em out.
- Those small bug fixes are of course fixed for a reason.
- We want to get the more responsive documentation site out.
- I don’t see anything coming that we should wait for to include in the release.

### CODE REVIEW

**Comment by jashkenas** [comment]
Running bin/cake doc:site ... and then re-saving index.html ... should normally cause all of those files to be recompiled. (Basically, just working on the index page).

However, I think that the file watching thing has been a little hinkey lately. Might make sense to add a task to just recompile them

**Comment by jashkenas** [comment]
Re: changelog -- feel free to elaborate on the bug fixes:

  * Several minor bug fixes, including: ...

**Comment by lydell** [comment]
Run `cake doc:site` in the background caused index.html to be recompiled from documentation/index.html.js. With the watcher still running in the background and `touch documentation/index.html.js` caused index.html to be recompiled once again. `touch index.html` caused nothing. The documentation/coffee/*.js files remained unchanged.

I can run `bin/coffee -bc documentation/coffee` to rebuild them, though. Should I do that?

Re: changelog—OK, I’ll add a sublist of really short summaries.

**Comment by lydell** [comment]
I’ve updated the PR with summaries of some of the small bug fixes and re-compiled documentation/coffee/*.js files now.

I’m still interested in this, though.

> Still, why are there seemingly duplicate compiled versions?

**Comment by jashkenas** [comment]
> I can run bin/coffee -bc documentation/coffee to rebuild them, though. Should I do that?

Sounds good.

> Still, why are there seemingly duplicate compiled versions?

They're probably a mistake. We should just delete the copies that aren't being used by index.html.

**Comment by lydell** [comment]
Alright. Then I think this PR is good-to-go, unless there are more changelog adjustments requested. I’ll try to remove the unnecessary files in a different PR.

**Comment by jashkenas** [comment]
Published, tagged, pushed.

Thanks, @lydell — This was the first 100% no-work painless release I can remember. Nicely done.

**Comment by lydell** [comment]
Thanks. However, I didn’t expect this to be merged today, so I set the release date to tomorrow ^^ Does it matter?

(Also, I just found a regression in the CSS—I’ll send a PR in a few minutes.)

**Comment by lydell** [comment]
Actually, it is not a regression. But the problem is still there. Look at that weird inline code at http://coffeescript.org/#1.10.0.

**Comment by lydell** [comment]
Ah, it’s because of the line wrapping in the HTML source code. The easiest thing would be to just not line wrap inside that `<code>` tag.

**Comment by lydell** [comment]
@jashkenas #4082.

**Comment by lydell** [comment]
And here’s the PR for removing the duplicate compiled files: #4083.

**Comment by jashkenas** [comment]
Pushed and pushed. You know you can just push those little things yourself, whenever you'd like, if you'd rather...

**Comment by carlsmith** [comment]
@lydell - Just wanted to say thanks from us users. You've done a ton of valuable stuff lately.

**Comment by nickdima** [comment]
kudos to @lydell ! keep them coming! :+1:

**Pull request merged**
