### PR TITLE
strip \r (if present) before final \n

### PR DESCRIPTION
**Pull request by shreeve**
Fixes 'cake test', which was failing due to "\r\n" terminators

### CODE REVIEW

**Comment by lydell** [comment]
This sounds like #4319. Could you please look through the comments over there, and then say if this PR is still relevant or not?

**Comment by shreeve** [comment]
Thanks for the reference to #4319, and yes this is the same issue. It appears to affect Mac OS only.

This PR has a better fix than the one from #4319 and should safely close both issues.

**Comment by lydell** [comment]
So the Node.js version doesn’t matter for you?

**Comment by shreeve** [comment]
I just upgraded to node 6.7.0 and this PR is not required.

Perhaps it was a transient thing that only impacted node versions on Mac between 6.4.x and 6.6.x?

Having said that, this small fix might help  people on those versions and shouldn't hurt anything otherwise. It just just does this:

```diff
-    @written[@written.length - 1 + fromEnd].replace /\n$/, ''
+    @written[@written.length - 1 + fromEnd].replace /\r?\n$/, ''
```

**Pull request merged**
