### PR TITLE
Include browser version in extras directory

### PR DESCRIPTION
**Pull request by XVincentX**
Will solve #4048

### CODE REVIEW

**Comment by michaelficarra** [comment]
Nope, this should not be distributed with the npm package. If you want it, extract it from the appropriate [github release](https://github.com/jashkenas/coffeescript/releases).

**Comment by XVincentX** [comment]
Hey,thank you for your prompt reply.
According to your use case, I think I am missing something. How do I import the client side version of coffeescript from the Npm package?

**Comment by michaelficarra** [comment]
You wouldn't. You can use bower to install CoffeeScript (including the browser build) or just fetch one of the release tarballs. npm distributes the files that are meant to be consumed by node when CoffeeScript is installed globally or as the dependency of a node project.

**Comment by XVincentX** [comment]
I disagree.Today npm modules are not only used for node project, but for frontend dependencies as well. See angular, jquery, hammerjs, moment, minim and so on.
But I respect your position; that is why the fork button actually exists ;)

**Comment by bjmiller** [comment]
If you're using CS for browser code, then use browserify with coffeeify.  Making the user take the performance hit of local transpilation is probably a bad idea.

**Comment by XVincentX** [comment]
Hey,I am already using webpack with coffee-script loader, but I have a live editing part that should be transformed in the browser.
Thanks anyway for the tip.

**Comment by bjmiller** [comment]
In that case...  You can point npm to the github address, and it will download master.  That should have what you need.

**Comment by XVincentX** [comment]
I am afraid it won't do the trick. `.npmignore` file still gets respected.
Tested with
`npm install jashkenas/coffeescript#master`

and
`npm install jashkenas/coffeescript#2d1a6fa6ec76b4e721da7e5e4a9c6b90172309ae`

**Comment by bjmiller** [comment]
I wonder if it makes sense to publish a separate entry in npm for just this one thing?  Just musing...

**Comment by michaelficarra** [comment]
npm is just not the right tool for the job here. Bower or cURL/tar are what you want.

**Comment by XVincentX** [comment]
Michael, are you sure of that? Personal experiences? Documentation?
http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

**Comment by michaelficarra** [comment]
Yep, that article basically makes the point for me. They point out a bunch of the pain points of using npm for managing front-end dependencies and show how bower solves those better. Package managers are designed with specific contexts, use cases, and distribution models in mind. npm wanting to be the single package manager for *all things JavaScript* is laughable.

**Comment by XVincentX** [comment]
I see the article on the other side, but ok, your point of view is clear and I respect that.
Thanks!

**Comment by XVincentX** [comment]
Ok, I see your point of view and I respect it.
Thanks!

**Pull request closed without merging**
