### PR TITLE
Add support for standalone yield

### PR DESCRIPTION
**Pull request by alubbe**
This breaks compatibility with
```coffee
->
  yield for i in [1..3]
    i * 2
```
and
```coffee
->
  yield
    i * 2
```
yield's behaviour now mirrors that of return in that it can be used stand alone as well as with expressions. Thus, it currently also inherits the above limitations.

### CODE REVIEW

**Comment by vendethiel** [comment]
LGTM :+1: . Nice work on these PRs :).

**Comment by alubbe** [comment]
It would be great to reenable the above, also for `return`. See https://github.com/jashkenas/coffeescript/issues/3357

**Comment by alubbe** [comment]
Also, thanks so much to @lydell for being an awesome pair on these 3 PRs :+1:

**Comment by vendethiel** [comment]
> yield's behaviour now mirrors that of return in that it can be used stand alone as well as with expressions. Thus, it currently also inherits the above limitations.

The only construct(s) that do not follow this rule, AFAIK, are function calls (and even those are very strict in what they allow) and functions (that's the implicit block rule)

**Comment by alubbe** [comment]
Just to understand it a bit further, what is the consensus here, should the above cases be legal coffee-script?

**Comment by vendethiel** [comment]
I think it should be allowed if possible (much the same for `return`)

**Comment by lydell** [comment]
Agreed. Either way, it’s out of scope for this PR.

**Comment by jashkenas** [comment]
Bravo.

**Pull request merged**
