### PR TITLE
Support `1_000.toString()`; fixes #5427

### LINKED ISSUE #5427: Bug: Numeric literal with numeric literal separator doesn't handle method call correctly
### Input Code

```coffee
1_000.toString()
```

### Expected Behavior

```javascript
1_000..toString()
```

### Current Behavior
```javascript
1_000.toString()
```

* CoffeeScript version: 2.7.0

### PR DESCRIPTION
**Pull request by STRd6**

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
Thank you!

**Comment by Inve1951** [comment]
`(?:\d(?:_?\d)*)+` can also be just
`\d(?:_?\d)*` without changing it's meaning

**Comment by GeoffreyBooth** [comment]
> `(?:\d(?:_?\d)*)+` can also be just
> 
> `\d(?:_?\d)*` without changing it's meaning

Wanna push a follow up PR?

**Comment by edemaine** [comment]
While we're optimizing, I think `\d+(?:_\d+)*` might be better (should confuse the backtracker less, expresses intent more clearly?).

**Pull request merged**
