### PR TITLE
Fix 5085

### PR DESCRIPTION
**Pull request by brewingcode**
Thanks for all the great work with CoffeeScript, I was just trolling through the issues and this looked like a simple fix. The fix is based on an assumption that I could be _completely_ wrong about, but according to the tests (including the new test for the bug itself), the assumption is correct.

### CODE REVIEW

**Comment by brewingcode** [comment]
Force-pushed small change the wording of the commit: "Assuming that a **bound** Code block..."

**Comment by brewingcode** [comment]
....and one more force-push to remove an unnecessary step from the test.

**Comment by GeoffreyBooth** [comment]
Thanks for this! @connec do you care to take a look?

**Comment by GeoffreyBooth** [comment]
@connec or @zdenko or @helixbass, anyone familiar with the `Class` node have a minute to review a one-line fix?

**Comment by vendethiel** [comment]
Can you please add a test for `class A then fn(b: => ...)`?

**Comment by brewingcode** [comment]
@vendethiel Sorry, I don't follow: what do you want the test to do?

**Comment by vendethiel** [comment]
Make sure the function inside the call inside an object is bound to the class (we shouldn’t attribute a name outside of class properties IIRC so the test should already work).

**Comment by brewingcode** [comment]
I'm not totally sure if this is what you meant...?

222067d

If it's not, could you just write the exact code you mean? Sorry that I'm just not getting it.

**Comment by vendethiel** [comment]
```
myvar = 0
fn = (o) -> o.prop()
class Klass
  @foo = 1
  fn prop: => myvar = @foo
```

**Comment by brewingcode** [comment]
```
class Klass
  fn prop: => myvar = @foo
```
I don't understand what this is doing at all, or what the intent of writing it would be, but OK, test added. :-)

Is `myvar` _supposed_ to be 1 after this...?

**Comment by vendethiel** [comment]
There was an old bug where we considered object properties outside of the class top-level and gave them names, just adding a test.

**Comment by GeoffreyBooth** [comment]
So @vendethiel is this okay to merge?

**Comment by vendethiel** [comment]
LGTM

**Comment by GeoffreyBooth** [comment]
Thanks @brewingcode!

**Comment by brewingcode** [comment]
You're welcome!

**Pull request merged**
