### PR TITLE
[CS2] Fix non-bare `get` `set` when called with `@` argument

### LINKED ISSUE #4524: [CS2] `get` as method should not require parentheses
This should not throw an error:

    location = App.locationCollection.get @model.get('location')
                                      ^^^
    ParseError: 'get' cannot be used as a keyword, or as a function call without parentheses

We should find a way to detect when `get` is used as `.get`, rather than bare `get`; and restrict the error to only the latter.

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Fixes #4524.

### CODE REVIEW

**Comment by vendethiel** [comment]
I think we could use three more tests (I don't think they're present yet):

```
get 5 # get without parentheses in an unambiguous
get {a: 5} # same
@get 5 # with `@`
```

Nicely done.

**Comment by GeoffreyBooth** [comment]
@vendethiel I’ve added some more tests. How does it look?

**Comment by vendethiel** [comment]
That looks good :).

**Comment by GeoffreyBooth** [comment]
Thanks!

**Pull request merged**
