### PR TITLE
Fixed link to Groovy doc link

### PR DESCRIPTION
**Pull request by casidiablo**

### CODE REVIEW

**Comment by vendethiel** [comment]
Hi,

the documentation file you'll want to change is [](https://github.com/jashkenas/coffeescript/blob/master/documentation/index.html.js)

**Comment by casidiablo** [comment]
Thanks

**Comment by lydell** [comment]
Great! Now just remove that first commit and we should be good to go!

**Comment by casidiablo** [comment]
:+1:

**Comment by vendethiel** [comment]
Thanks! :+1:

**Pull request merged**
