### PR TITLE
fixed yield return producing incorrect output when used outside of the last line

### PR DESCRIPTION
**Pull request by alubbe**
Fixes https://github.com/jashkenas/coffeescript/issues/3837

### CODE REVIEW

**Comment by alubbe** [comment]
rebased.

**Comment by alubbe** [comment]
any feedback @jashkenas @michaelficarra ?

**Comment by jashkenas** [comment]
I don't really understand why `yield return`s need to be handled specially, but ...

I think this PR could use a more robust test, where `yield return`s existed in various different branches of a function body. Maybe a complicated `if`? Maybe with a loop in it?

**Comment by vendethiel** [comment]
It's not a JS construct. It's a coffee construct.

**Comment by michaelficarra** [comment]
I think `yield return` anywhere but the last position in the body should be an error.

**Comment by alubbe** [comment]
made the test a bit more complicated and added an error into the last (unreachable) line

**Pull request merged**
