### PR TITLE
Update dependency on mkdirp

### PR DESCRIPTION
**Pull request by flowlo**

### CODE REVIEW

**Comment by lydell** [comment]
Why isn’t this merged?

**Comment by michaelficarra** [comment]
Does it fix any open issues?

**Comment by flowlo** [comment]
My idea was to fix this outdated dependency:

```bash
$ npm install coffee-script
coffee-script@1.8.0 node_modules/coffee-script
└── mkdirp@0.3.5

$ npm outdated
Package  Current  Wanted  Latest  Location
mkdirp     0.3.5   0.3.5   0.5.0  coffee-script > mkdirp
```

**Comment by michaelficarra** [comment]
That doesn't fix a bug or add a new feature. :-1:

**Comment by lydell** [comment]
Latest isn’t always best. I just checked through the commit history of mkdirp since 0.3.5. The only changes are:

- Updated docs
- Added `opts.fs` optio
- Added CLI

So the only effect of updating would be adding minimist (which mkdirp uses for its CLI) as a sub-dependency.

**Pull request closed without merging**
