### PR TITLE
CoffeeScript 1.9.3

### PR DESCRIPTION
**Pull request by lydell**
There are a few nice bugfixes just waiting to be released :) The most important ones, IMO, are the source map fix and REPL error messages fix. There’s also a bunch of new documentation that would be nice to get out.

### CODE REVIEW

**Comment by michaelficarra** [comment]
:+1:

**Comment by vendethiel** [comment]
LGTM

**Comment by lydell** [comment]
Ping @jashkenas.

**Comment by lydell** [comment]
Pinging @jashkenas again, since he replied in another issue ;P

**Comment by jashkenas** [comment]
Sorry -- I've got a big email pile in the "Github" tab. If you actually want to get my attention, you'll have to shoot me a direct email.

... but looking now.

**Comment by jashkenas** [comment]
Many thanks, @lydell. Great work. Published.

**Comment by lydell** [comment]
Perhaps the release date should be adjusted. It currently says 14 May.

**Comment by jashkenas** [comment]
Thanks, updated.

**Pull request merged**
