### PR TITLE
1.12.3

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
We should release #4428 ASAP.

### CODE REVIEW

**Comment by lydell** [comment]
I think we need to mention this in the changelog, too:

```
commit 1143ac0268f3d96354ef156e78435716368053f6
Author: Chris Connelly <chris.connelly@cloudreach.com>
Date:   2016-12-29 18:55:33 +0000

    Allow `@` values as indices in `for` expressions
    
    This loosens the compilation of `for` expressions to allow the index
    variable to be an `@` value, e.g.
    
        do @visit for @node, @index in nodes
    
    Within `@visit`, the index of the current node (`@node`) would be
    available as `@index`.
    
    Fixes #4411.

commit 0a6aeef0c9426ad5af177673190e196dcf2849e9
Author: Valentine Valyaeff <val@magazon.net>
Date:   2016-12-23 15:37:11 +0200

    Fix //= operator (#4410)

```

**Comment by GeoffreyBooth** [comment]
Whoops, thanks. Added.

**Comment by GeoffreyBooth** [comment]
@lydell

**Comment by lydell** [comment]
Released.

**Pull request merged**
