### PR TITLE
document try without catch nor finally

### PR DESCRIPTION
**Pull request by SonOfLilit**
try without catch/finally is not documented #3958

### CODE REVIEW

**Comment by SonOfLilit** [comment]
Should I have compiled the .coffee example to .js, or is this done automatically when uploading to the website? I couldn't find a guide on doing it, I assume I could just look in the build system config though.

**Comment by jashkenas** [comment]
I think it's already documented adequately. But thanks.

> Try-expressions have the same semantics as try-statements in JavaScript, though in CoffeeScript, you may omit both the catch and finally parts.

**Comment by SonOfLilit** [comment]
I've asked a fellow programmer and he expected behavior to be not to suppress exceptions when `catch` is omitted.

Can I ask you to poll 3-4 non-CoffeeScript programmers on how they understood the existing documentation, and decide whether additional clarification is needed based on their responses? (Or if you trust me, I could do the experiment and report results.)

**Comment by socketpair** [comment]
I prefer that `try` without a `catch` should be `syntax error`. Even in form `try xxx=do_some_fun()`.

Exceptions in javascript is very sensitive thing, so syntactically hiding situation where exception is swallowed is a very BAD thing.

**Comment by carlsmith** [comment]
Maybe I missed something, but if a lone try-statement did not "suppress" exceptions, what should it do? You may not like the form, but is not ambiguous, in that there is only one sane expectation, which is the correct one.

**Pull request closed without merging**
