### PR TITLE
Reorganize docs for v1/v2 split

### LINKED ISSUE #4295: Dead links at coffeescript.org
I found dead links at coffeescript homepage.
For instance:
_jashkenas' Underscore.coffee, a port of the Underscore.js library of helper functions._
http://coffeescript.org/documentation/docs/underscore.html
http://documentcloud.github.io/underscore/

Above links lead to 404 error page.

I suppose that the following file is responsible for it:
https://github.com/jashkenas/coffeescript/blob/master/index.html

May I ask for guidance on how to proceed with pull requests, forks etc? I would love to contribute by resolving this issue.

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
This moves the generated documentation files into `docs/v1`, with `docs/index.html` symlinked to `docs/v1/index.html`. Static assets like images are moved under `docs/v1`. Generated source is under `docs/v1/annotated-source`. `Cakefile` is updated to save generated files into these new paths. See demo: https://geoffreybooth.github.io/coffeescript/

Other updates:
* The missing `underscore.html` is now in `docs/v1/annotated-source`. Closes #4295.
* The included jQuery was removed in favor of Google’s hosted version.
* Updated dependencies; removed check for `--harmony` before running generators tests.
* All references to coffeescript.org now say **https**://coffeescript.org.

@jashkenas Once this is merged in, go to the repo Settings page and under GitHub Pages change Source to `master branch /docs folder` **and** check `Enforce HTTPS`.

### CODE REVIEW

**Comment by lydell** [comment]
Awesome work! :+1:

**Comment by jashkenas** [comment]
Did it -- but looks like the site is down now because maybe our CNAME file isn't in the right place? Trying to fix...

**Comment by jashkenas** [comment]
There we go. Fixed it. Good luck with the `/v2` !

**Comment by GeoffreyBooth** [comment]
@jashkenas Did you turn on HTTPS? The links in the code now are for https://coffeescript.org.

**Comment by jashkenas** [comment]
I did, but HTTPS doesn't work for Github pages with custom domains.

image

If you don't mind reverting the links to HTTP, that would be lovely.

For more, see: https://github.com/isaacs/github/issues/156

**Comment by GeoffreyBooth** [comment]
Okay, I’ve reverted them.

**Pull request merged**
