### PR TITLE
Rebuild browser file

### PR DESCRIPTION
**Pull request by mbrio**
While looking into the issues that were plaguing reactjs/react-ruby (https://github.com/jashkenas/coffeescript/issues/3829#issuecomment-74134197) I found that the browser JS file did not match the compiled output from the 1.9.0 source code. I believe this is why the error was occurring.

### CODE REVIEW

**Comment by michaelficarra** [comment]
I did a `git checkout 1.9.0` and ran `cake build:browser`. It caused no changes to `extras/coffee-script.js`, and is different than the file in this PR. Closing as I cannot reproduce this issue or the submitted file in this PR.

**Comment by mbrio** [comment]
Admittedly, I didn't git checkout 1.9.0 I think I was using master. The error above was definitely fixed when I recompiled the latest code's browser file. So either the error has been fixed and not released or could an update to a third party package fix it. Unfortunately I'm not in front of a computer, when the JS is compiled is it injecting JS from other libraries?

I only mention this because the error is occurring when assigning a root property on a null object. In the coffee src, root only appears in one place, but in the compiled JS root appears numerous times.

If you checkout 1.9.0 and re-install your node_modules, is the output still the same? This would mean that the error actually originated from a third-party module.

**Comment by michaelficarra** [comment]
I did re-install my node_modules, and it built an identical file to what is in 1.9.0. It is possible this has been fixed somehow on master, but I do not recall anything.

**Comment by mbrio** [comment]
@michaelficarra, I just responded on a previous thread that corresponds with this error (https://github.com/jashkenas/coffeescript/issues/3829#issuecomment-74134197) and described what I had found in the time I had trying to figure out what the problem was.

It's interesting to note that @koron states (https://github.com/jashkenas/coffeescript/issues/3829#issuecomment-75706760) that node 0.12 fixes the problem.

**Pull request closed without merging**
